# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\unfal\Documents\Cool Stuff\Purple-Rain"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\unfal\Documents\Cool Stuff\Purple-Rain"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\unfal\Documents\Cool Stuff\Purple-Rain\CMakeFiles" "C:\Users\unfal\Documents\Cool Stuff\Purple-Rain\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\unfal\Documents\Cool Stuff\Purple-Rain\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CAD

# Build rule for target.
CAD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 CAD
.PHONY : CAD

# fast build rule for target.
CAD/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/build
.PHONY : CAD/fast

src/GradientRain.obj: src/GradientRain.cpp.obj
.PHONY : src/GradientRain.obj

# target to build an object file
src/GradientRain.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/GradientRain.cpp.obj
.PHONY : src/GradientRain.cpp.obj

src/GradientRain.i: src/GradientRain.cpp.i
.PHONY : src/GradientRain.i

# target to preprocess a source file
src/GradientRain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/GradientRain.cpp.i
.PHONY : src/GradientRain.cpp.i

src/GradientRain.s: src/GradientRain.cpp.s
.PHONY : src/GradientRain.s

# target to generate assembly for a file
src/GradientRain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/GradientRain.cpp.s
.PHONY : src/GradientRain.cpp.s

src/Poly.obj: src/Poly.cpp.obj
.PHONY : src/Poly.obj

# target to build an object file
src/Poly.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/Poly.cpp.obj
.PHONY : src/Poly.cpp.obj

src/Poly.i: src/Poly.cpp.i
.PHONY : src/Poly.i

# target to preprocess a source file
src/Poly.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/Poly.cpp.i
.PHONY : src/Poly.cpp.i

src/Poly.s: src/Poly.cpp.s
.PHONY : src/Poly.s

# target to generate assembly for a file
src/Poly.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/Poly.cpp.s
.PHONY : src/Poly.cpp.s

src/app.obj: src/app.cpp.obj
.PHONY : src/app.obj

# target to build an object file
src/app.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/app.cpp.obj
.PHONY : src/app.cpp.obj

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/pge/olcPixelGameEngine.obj: src/pge/olcPixelGameEngine.cpp.obj
.PHONY : src/pge/olcPixelGameEngine.obj

# target to build an object file
src/pge/olcPixelGameEngine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/pge/olcPixelGameEngine.cpp.obj
.PHONY : src/pge/olcPixelGameEngine.cpp.obj

src/pge/olcPixelGameEngine.i: src/pge/olcPixelGameEngine.cpp.i
.PHONY : src/pge/olcPixelGameEngine.i

# target to preprocess a source file
src/pge/olcPixelGameEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/pge/olcPixelGameEngine.cpp.i
.PHONY : src/pge/olcPixelGameEngine.cpp.i

src/pge/olcPixelGameEngine.s: src/pge/olcPixelGameEngine.cpp.s
.PHONY : src/pge/olcPixelGameEngine.s

# target to generate assembly for a file
src/pge/olcPixelGameEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/pge/olcPixelGameEngine.cpp.s
.PHONY : src/pge/olcPixelGameEngine.cpp.s

src/utils/utils.obj: src/utils/utils.cpp.obj
.PHONY : src/utils/utils.obj

# target to build an object file
src/utils/utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/utils/utils.cpp.obj
.PHONY : src/utils/utils.cpp.obj

src/utils/utils.i: src/utils/utils.cpp.i
.PHONY : src/utils/utils.i

# target to preprocess a source file
src/utils/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/utils/utils.cpp.i
.PHONY : src/utils/utils.cpp.i

src/utils/utils.s: src/utils/utils.cpp.s
.PHONY : src/utils/utils.s

# target to generate assembly for a file
src/utils/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\CAD.dir\build.make CMakeFiles/CAD.dir/src/utils/utils.cpp.s
.PHONY : src/utils/utils.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... CAD
	@echo ... src/GradientRain.obj
	@echo ... src/GradientRain.i
	@echo ... src/GradientRain.s
	@echo ... src/Poly.obj
	@echo ... src/Poly.i
	@echo ... src/Poly.s
	@echo ... src/app.obj
	@echo ... src/app.i
	@echo ... src/app.s
	@echo ... src/pge/olcPixelGameEngine.obj
	@echo ... src/pge/olcPixelGameEngine.i
	@echo ... src/pge/olcPixelGameEngine.s
	@echo ... src/utils/utils.obj
	@echo ... src/utils/utils.i
	@echo ... src/utils/utils.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

